import { Command } from "commander";
import packageJSON from "../package.json" with { type: "json" };
import fs, { readFile, writeFile } from "fs/promises";
import { spawn } from "child_process";
import pathlib from "path";
import type { IPluginDefinition } from "@sourceacademy/plugin-directory/dist/types/IPluginDefinition.js";
import process from "process";
const program = new Command();
interface Manifest {
  type: "installable" | "external";
}

const globalManifest: Record<string, Record<string, Manifest>> = {};
const pluginDirectory: Record<string, IPluginDefinition> = {};

/**
 * Generates the manifest files for each plugin and updates the changeset config to ignore non-installable plugins.
 * The manifest files are generated by reading the manifest.json file in each plugin folder and writing it to the dist folder.
 * The changeset config is updated to ignore non-installable plugins to prevent unnecessary version bumps and releases.
 * @example
 * await generateManifest();
 * This will generate the manifest files for each plugin and update the changeset config to ignore non-installable plugins.
 */
async function generateManifest() {
  // Create dist directory if it doesn't exist
  await fs.mkdir("dist", { recursive: true });

  // The ignore list is used to keep track of non-installable plugins, which should be ignored in changesets to prevent unnecessary version bumps and releases.
  const ignoreList: string[] = [];

  await Promise.all(
    packageJSON.workspaces.map(async workspace => {
      const manifest: Record<string, Manifest> = {};
      // pluginType is either "web", "runner" or "common"
      const pluginType = workspace.split("/").slice(-3)[0];
      for await (const file of fs.glob(`${workspace}manifest.json`)) {
        const manifestFile = JSON.parse(await fs.readFile(file, "utf-8"));
        const packageJSONPath = file.replace("manifest.json", "package.json");
        const packageJSONFile = JSON.parse(await fs.readFile(packageJSONPath, "utf-8"));
        // folderName is the name of the plugin folder (generally the same as the plugin name)
        const folderName = file.split(pathlib.sep).slice(-2)[0];
        manifest[folderName] = manifestFile as Manifest;
        if (manifestFile.type !== "installable") {
          ignoreList.push(`@sourceacademy/${pluginType}-${folderName}`);
          pluginDirectory[folderName] = pluginDirectory[folderName] || {
            id: folderName,
            name: folderName,
            description: packageJSONFile.description,
            resolutions: {},
          };
          pluginDirectory[folderName].resolutions[pluginType] =
            "./" + pluginType + "/" + folderName + "/index.js";
        }
      }
      globalManifest[pluginType] = manifest;
      await fs.writeFile(`dist/${pluginType}.json`, JSON.stringify(manifest, null, 2));
    }),
  );

  // Write the plugin directory to the dist folder. This is used by the plugin loaders to load non-installable plugins.
  await fs.writeFile(
    `dist/directory.json`,
    JSON.stringify(Object.values(pluginDirectory), null, 2),
  );

  // Update changeset config to ignore non-installable plugins
  const changesetConfig = await fs.readFile(".changeset/config.json", "utf-8");
  const changesetConfigJSON = JSON.parse(changesetConfig);
  changesetConfigJSON.ignore = ignoreList;
  await fs.writeFile(".changeset/config.json", JSON.stringify(changesetConfigJSON, null, 2));
}

/**
 * A helper function to spawn a child process and return a promise that resolves when the process exits with code 0, and rejects otherwise.
 * @param args The arguments passed to spawn
 * @returns A promise that resolves when the process exits with code 0, and rejects otherwise.
 * @example
 * await spawnPromise("yarn", ["build"]);
 */
async function spawnPromise(...args: Parameters<typeof spawn>) {
  return new Promise<void>((resolve, reject) => {
    const child = spawn(...args);
    child.on("close", code => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

/**
 * Copies the dist files from each "external" plugin (i.e. plugins that are bundles) to the dist folder.
 * This is necessary because the dist files are not included in the workspace build process, and we need to copy them manually to the dist folder for them to be included in the final build output.
 * @example
 * await copyDistFiles();
 */
async function copyDistFiles() {
  await Promise.all(
    // Iterate over each plugin type (web, runner, common)
    Object.entries(globalManifest).map(async ([pluginType, manifest]) => {
      await Promise.all(
        // Iterate over each plugin in the plugin type and copy the dist files if the plugin is of type "external"
        Object.entries(manifest).map(async ([pluginName, pluginManifest]) => {
          if (pluginManifest.type === "external") {
            await fs.cp(
              `src/${pluginType}/${pluginName}/dist`,
              `dist/${pluginType}/${pluginName}`,
              { recursive: true },
            );
          }
        }),
      );
    }),
  );
}

/**
 * Builds the plugins by generating the manifest and running the build script for each plugin.
 * The build script is run in topological order to ensure that dependencies are built before the plugins that depend on them.
 * @param extraArgs Extra arguments to pass to the build script of each plugin. For example, if you want to run the build script in watch mode, you can pass ["--watch"] as extraArgs.
 * @example
 * await build(["--watch"]);
 * This will run the build script of each plugin with the --watch flag, which is useful for development.
 */
async function build(extraArgs: string[] = []) {
  await Promise.all([
    generateManifest(),
    spawnPromise(
      process.platform === "win32" ? "yarn.cmd" : "yarn",
      ["workspaces", "foreach", "-Apt", "--topological-dev", "run", "build", ...extraArgs],
      {
        stdio: "inherit",
        shell: true,
      },
    ),
  ]);
  await copyDistFiles();
  await transform();
}

/**
 * Transforms a particular external plugin to its final form
 */
async function transformSingle(path: string) {
  if (path.endsWith("mjs")) {
    return;
  }
  let file = (await readFile(path)).toString("utf-8");

  // Create a mock "module" object, then return the exports
  file = `export default require => {let module = {exports: {}}; let exports = module.exports; ${file}; return module.exports;}`;
  await writeFile(path, file);
}

/**
 * Transforms the plugins to its final form
 * For external plugins, this wraps it in an "export default require => { ... }" or "export default import => { ... }"
 */
async function transform() {
  const promises = [];
  for await (const file of fs.glob(`./dist/*/*/index.*js`)) {
    promises.push(transformSingle(file));
  }
  await Promise.all(promises);
}

// TO-DO: Add more options
const options = program.parse();
const extraArgs = options.args;
await build(extraArgs);
