import { exec, spawn } from 'child_process';
import fs from 'fs/promises';
import { createRequire } from 'module';
import pathlib from 'path';
import type { IPluginDefinition } from '@sourceacademy/plugin-directory/dist/types/IPluginDefinition.js';
import { Command } from '@commander-js/extra-typings';
import packageJSON from '../package.json' with { type: 'json' };

interface WorkspaceEntry {
  location: string;
  name: string;
}

interface Manifest {
  type: 'installable' | 'external';
}

/**
 * Use `yarn workspaces list --json` to gather all the workspaces in the repository
 */
async function getWorkspaces() {
  const entries = await new Promise<string[]>((resolve, reject) => {
    exec('yarn workspaces list --json', (err, stdout, stderr) => {
      if (err) {
        reject(err);
      }

      if (stderr) console.error(stderr);

      resolve(stdout.trim().split('\n'));
    });
  });

  return entries.map(each => JSON.parse(each)) as WorkspaceEntry[];
}

const repoRoot = pathlib.resolve(import.meta.dirname, '..');
// Create a `require` function to use node's resolution algorithm to find
// the entry point of plugins
const require = createRequire(import.meta.url);
const pluginDirectory: Record<string, IPluginDefinition> = {};

/**
 * Generates the manifest files for each plugin and updates the changeset config to ignore non-installable plugins.
 * The manifest files are generated by reading the manifest.json file in each plugin folder and writing it to the dist folder.
 * The changeset config is updated to ignore non-installable plugins to prevent unnecessary version bumps and releases.
 * @example ```
 * await generateManifest();
 * ```
 * This will generate the manifest files for each plugin and update the changeset config to ignore non-installable plugins.
 */
export async function generateManifest() {
  const globalManifest: Record<string, Record<string, Manifest>> = {};

  // Create dist directory if it doesn't exist
  const distDirectory = pathlib.join(repoRoot, 'dist');
  await fs.mkdir(distDirectory, { recursive: true });

  // The ignore list is used to keep track of non-installable plugins, which should be ignored in changesets to prevent unnecessary version bumps and releases.
  const ignoreList: string[] = [];

  const workspaces = await getWorkspaces();

  await Promise.all(
    workspaces.map(async ({ name: workspaceName, location }) => {
      // Don't process the root workspace
      if (workspaceName === packageJSON.name) return;

      const pkgMatch = /@sourceacademy\/(\w+?)-(.+)/.exec(workspaceName);

      if (!pkgMatch) throw new Error(`Invalid package name ${workspaceName}`);
      const [, pluginType, pluginName] = pkgMatch;

      if (!(pluginType in globalManifest)) {
        globalManifest[pluginType] = {};
      }

      const workspacePath = pathlib.resolve(repoRoot, location);
      const manifestFilePath = pathlib.join(workspacePath, 'manifest.json');
      const pkgJsonPath = pathlib.join(workspacePath, 'package.json');

      const [{ default: manifestFile }, { default: packageJSONFile }] = await Promise.all([
        import(`file://${manifestFilePath}`, { with: { type: 'json' } }),
        import(`file://${pkgJsonPath}`, { with: { type: 'json' } }),
      ]);

      const manifest = globalManifest[pluginType];
      manifest[pluginName] = manifestFile as Manifest;

      if (manifestFile.type !== 'installable') {
        ignoreList.push(workspaceName);

        pluginDirectory[pluginName] = pluginDirectory[pluginName] || {
          id: pluginName,
          name: pluginName,
          description: packageJSONFile.description,
          resolutions: {},
        };

        // Use the plugin's own declared entry point rather than assuming ".js": external
        // plugins can emit ".mjs" (e.g. the stepper's wrap.mjs produces real ESM for native
        // `import()`), and a mismatch here silently 404s for anyone resolving the plugin.
        const entryFile = pathlib.basename(require.resolve(workspacePath));

        pluginDirectory[pluginName].resolutions[pluginType] = pathlib.posix.join(
          '.',
          pluginType,
          pluginName,
          entryFile,
        );
      }
    }),
  );

  // Write the manifest for each plugin type to the dist folder.
  await Promise.all(
    Object.entries(globalManifest).map(([pluginType, manifest]) => {
      const outpath = pathlib.join(repoRoot, 'dist', `${pluginType}.json`);
      return fs.writeFile(outpath, JSON.stringify(manifest, null, 2));
    }),
  );

  // Write the plugin directory to the dist folder. This is used by the plugin loaders to load non-installable plugins.
  await fs.writeFile(
    pathlib.join(repoRoot, 'dist', 'directory.json'),
    JSON.stringify(Object.values(pluginDirectory), null, 2),
  );

  // Update changeset config to ignore non-installable plugins
  const changesetFilePath = pathlib.join(repoRoot, '.changeset', 'config.json');
  const { default: changesetConfigJSON } = await import(`file://${changesetFilePath}`, {
    with: { type: 'json' },
  });
  changesetConfigJSON.ignore = ignoreList;
  await fs.writeFile(changesetFilePath, JSON.stringify(changesetConfigJSON, null, 2));

  return globalManifest;
}

/**
 * Runs `yarn` with the given arguments.
 */
function runYarnUsingSpawn(...args: string[]) {
  return new Promise<void>((resolve, reject) => {
    const proc = spawn(process.platform === 'win32' ? 'yarn.cmd' : 'yarn', args, {
      stdio: 'inherit',
      shell: true,
      cwd: repoRoot,
    });
    proc.on('error', reject);
    proc.on('close', code => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Process exited with code ${code}`));
      }
    });
  });
}

/**
 * Copies the dist files from each "external" plugin (i.e. plugins that are bundles) to the dist folder.
 * This is necessary because the dist files are not included in the workspace build process, and we need to copy them manually to the dist folder for them to be included in the final build output.
 * @example
 * await copyDistFiles();
 */
async function copyDistFiles(globalManifest: Record<string, Record<string, Manifest>>) {
  await Promise.all(
    // Iterate over each plugin type (web, runner, common)
    Object.entries(globalManifest).map(async ([pluginType, manifest]) => {
      await Promise.all(
        // Iterate over each plugin in the plugin type and copy the dist files if the plugin is of type "external"
        Object.entries(manifest).map(async ([pluginName, pluginManifest]) => {
          if (pluginManifest.type === 'external') {
            await fs.cp(
              pathlib.join(repoRoot, 'src', pluginType, pluginName, 'dist'),
              pathlib.join(repoRoot, 'dist', pluginType, pluginName),
              { recursive: true },
            );
          }
        }),
      );
    }),
  );
}

/**
 * Transforms a particular external plugin to its final form
 */
async function transformSingle(path: string) {
  if (path.endsWith('mjs')) {
    return;
  }
  let file = await fs.readFile(path, 'utf-8');

  // Create a mock "module" object, then return the exports
  file = `export default require => {let module = {exports: {}}; let exports = module.exports; ${file}; return module.exports;}`;
  await fs.writeFile(path, file);
}

/**
 * Transforms the plugins to its final form
 * For external plugins, this wraps it in an "export default require => { ... }" or "export default import => { ... }"
 */
async function transform() {
  const promises = [];
  for await (const file of fs.glob(`./dist/*/*/index.*js`)) {
    promises.push(transformSingle(file));
  }
  await Promise.all(promises);
}

/**
 * Builds the plugins by generating the manifest and running the build script for each plugin.
 * The build script is run in topological order to ensure that dependencies are built before the plugins that depend on them.
 * @param extraArgs Extra arguments to pass to the build script of each plugin. For example, if you want to run the build script in watch mode, you can pass ["--watch"] as extraArgs.
 * @example
 * await build(["--watch"]);
 * This will run the build script of each plugin with the --watch flag, which is useful for development.
 */
async function build(extraArgs: string[] = []) {
  // Need to build first so that require.resolve doesn't break
  await runYarnUsingSpawn(
    'workspaces',
    'foreach',
    '-Apt',
    '--topological-dev',
    '--exclude',
    '@sourceacademy/plugins-workspace',
    'run',
    'build',
    ...extraArgs,
  );
  const globalManifest = await generateManifest();
  await copyDistFiles(globalManifest);
  await transform();
}

/**
 * Finds all the `dist` folders and deletes them, effectively "cleaning" the repo
 * of built artifacts
 */
async function clean() {
  const globPath = pathlib.join(repoRoot, '**', 'dist');

  const promises = [];
  for await (const file of fs.glob(globPath)) {
    promises.push(fs.rm(file, { recursive: true }));
  }
  await Promise.all(promises);
}

const program = new Command()
  .addCommand(
    new Command('build')
      .allowExcessArguments(true)
      .allowUnknownOption(true)
      .action(async (_, cmd) => {
        await build(cmd.args);
      }),
    { isDefault: true },
  )
  .addCommand(new Command('clean').description('Remove dist folders').action(clean));

// Only run automatically if not testing
if (process.env.NODE_ENV !== 'test') {
  await program.parseAsync();
}
