name: Build and deploy plugins
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Enable corepack
        run: corepack enable
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: yarn run build
        run: yarn run build 
      - name: Run tests
        run: yarn run test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          version: yarn changeset version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: dist/

  deploy:
    needs: build
    name: Deploy plugins
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
